// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A testimonial generator AI agent.
 *
 * - generateTestimonial - A function that handles the testimonial generation process.
 * - GenerateTestimonialInput - The input type for the generateTestimonial function.
 * - GenerateTestimonialOutput - The return type for the generateTestimonial function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTestimonialInputSchema = z.object({
  companyDescription: z
    .string()
    .describe('The description of the company or brand.'),
  slogan: z.string().describe('The slogan of the company or brand.'),
  preferredColors: z
    .string()
    .describe('The preferred colors for the brand.'),
});
export type GenerateTestimonialInput = z.infer<typeof GenerateTestimonialInputSchema>;

const GenerateTestimonialOutputSchema = z.object({
  testimonial: z.string().describe('The generated testimonial.'),
  author: z.string().describe('The author of the testimonial.'),
});
export type GenerateTestimonialOutput = z.infer<typeof GenerateTestimonialOutputSchema>;

export async function generateTestimonial(
  input: GenerateTestimonialInput
): Promise<GenerateTestimonialOutput> {
  return generateTestimonialFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTestimonialPrompt',
  input: {schema: GenerateTestimonialInputSchema},
  output: {schema: GenerateTestimonialOutputSchema},
  prompt: `You are an expert marketing copywriter specializing in writing customer testimonials for businesses in the beauty industry.

You will use the following information about the brand to generate a personalized testimonial from a satisfied customer. The testimonial should sound authentic and highlight the positive impact the brand has had.

Company Description: {{{companyDescription}}}
Slogan: {{{slogan}}}
Preferred Colors: {{{preferredColors}}}

The testimonial should be in Arabic, and the author name should be a common Arabic female name.

Make sure the testimonial is short and to the point, highlighting the best aspects of the brand.  Keep it under 30 words.
`,
});

const generateTestimonialFlow = ai.defineFlow(
  {
    name: 'generateTestimonialFlow',
    inputSchema: GenerateTestimonialInputSchema,
    outputSchema: GenerateTestimonialOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
